version: '3'

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - 'nexus-data:/nexus-data'
    ports:
      - '8081:8081'
      - '8082:8082'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
  frontend:
    image: 192.168.1.21:8082/deploy_module/front-modulo8:1.1.0
    ports:
      - '80:80'
  backend:
    image: 192.168.1.21:8082/deploy_module/back-modulo8:1.1.0
    ports:
      - '4000:4000'

volumes:
  nexus-data: {}